### ISSUE TITLE
1.19 UPDATE?

### ISSUE THREAD

**Issue by PolloEnCubitos** [Toshimichi0915/Thymine#13]
Hi tho, great mod i didnt find another alternative like this one for the 1.19 tho, im still using it on my mod pack 1.16.5

Im wondering if u have a free time to maybe update the mod to the 1.19 please?

Thanks and i will wait for ur answer!

**Comment by Toshimichi0915** [comment]
I'm working on 1.19 right now! Probably I can release 1.19 version in a few days

**Comment by PolloEnCubitos** [comment]
Thanks! if u use twitter or u have a discord server give me the links and i drop u a follow or join

**Comment by MyNameIsF** [comment]
still no 1.19

**Comment by Toshimichi0915** [comment]
https://github.com/Toshimichi0915/Thymine/releases/tag/v1.7.2
I have uploaded 1.19 version! Could you reply me if that works?, then I can close this issue.

**Comment by Toshimichi0915** [comment]
@MyNameIsF @PolloEnCubitos

**Comment by PolloEnCubitos** [comment]
Yup it appear to be working fine, i already test it 1 hour without any problem if i found a bug im just going to open a new issue
