### ISSUE TITLE
Incompatibility with Minecraft 1.19.3

### ISSUE THREAD

**Issue by Leomelonseeds** [Toshimichi0915/Thymine#16]
When trying to open the "Options" menu from the main menu when loading Thymine 1.8.1 with Minecraft 1.19.3, the game crashes and the following crash report is made: https://pastebin.com/jjn7rfaA

Removing Thymine fixes this issue. Thanks for your time.

**Comment by Toshimichi0915** [comment]
https://github.com/Toshimichi0915/Thymine/releases/tag/v1.8.2

Fixed.
Thank you for the crash report.
