### ISSUE TITLE
low fire causes black fire when player is on fire

### ISSUE THREAD

**Issue by MyNameIsF** [Toshimichi0915/Thymine#6]
![2021-07-31_23 49 32](https://user-images.githubusercontent.com/87782749/127752124-d4797924-f648-4c0d-a3c3-f7f326d9bdf0.png)
![2021-07-31_23 49 38](https://user-images.githubusercontent.com/87782749/127752126-4b22d1b9-28cd-4e7f-b886-08639013e9df.png)

**Comment by Toshimichi0915** [comment]
What mods are you using?
Also, please tell me the version of minecraft

**Comment by Toshimichi0915** [comment]
@MyNameIsF

**Comment by MyNameIsF** [comment]
Sorry for late reply im using lot of mods i can send the mods file here and version is 1.17.1 also i tried not using any texture packs and it didnt work
[mods.zip](https://github.com/Toshimichi0915/giz5/files/6947802/mods.zip)

**Comment by Toshimichi0915** [comment]
Fixed
[Download](https://github.com/Toshimichi0915/Thymine/releases/tag/v1.6.1)
