### ISSUE TITLE
Can't disable lowfire

### ISSUE THREAD

**Issue by MyNameIsF** [Toshimichi0915/Thymine#7]
there is no option to disable lowfire

**Comment by Toshimichi0915** [comment]
Set low fire height to 0% and the fire height will be the same as vanilla.
Also, if you haven't downloaded the latest version, make sure to download.
![image](https://user-images.githubusercontent.com/26406334/132094677-825c7690-be38-4901-8cf7-1e3d2c060bef.png)

**Comment by Toshimichi0915** [comment]
If that works, please close the issue.
If that doesn't work, please tell me what's wrong
:)
