### ISSUE TITLE
1.16

### ISSUE THREAD

**Issue by nguyendog** [Toshimichi0915/Thymine#8]
Can you create Thymine for 1.16? I use 1.16 a lot to PvP

**Comment by nguyendog** [comment]
Thanks for helping :D

**Comment by Toshimichi0915** [comment]
I made 1.16 version.
If you are satisfied with this, Please add star to this repository & close the issue.
https://github.com/Toshimichi0915/Thymine/releases/tag/v1.7.2

**Comment by nguyendog** [comment]
Thank you!
This is AMAZING!
