### ISSUE TITLE
[Enhancement] Add a button to toggle LowFire 

### ISSUE THREAD

**Issue by MyNameIsF** [Toshimichi0915/Thymine#9]
I know that you can make low fire 0%. But still adding a button would be an enhancement.

**Comment by Toshimichi0915** [comment]
Can you please tell me why the option should be added?

**Comment by MyNameIsF** [comment]
Because it would be easier to turn off low fire.

**Comment by Toshimichi0915** [comment]
I don't think that makes things easier
